version: '3'
services:
  app:
    container_name: nextjs-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
    command: npm run dev

  backend:
    container_name: springboot-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080