spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring:
  jpa:
    show-sql: true
  r2dbc:
#    url: r2dbc:h2:file:///~/db/testdb
    url: r2dbc:h2:mem:///testdb
  flyway:
#    url: jdbc:h2:file:~/db/testdb
    url: jdbc:h2:mem:testdb
    locations: classpath:/db/migration
    enabled: true